"""
The consented starter-spread batch offered during onboarding.

Curated by the user from their own spread library (2026-09-03) —
extracted from the live database, with 'Lenormand' deck-type
restrictions updated to the current 'Petit Lenormand' name, and the
Grand Tableau (8x4+4) derived from the 9x4's geometry. Regenerate by
re-extracting rather than hand-editing positions.
"""

STARTER_SPREADS = [{'name': 'Single Card',
  'description': 'One card: a daily draw, a focus, an answer.',
  'positions': [{'x': 220,
                 'y': 60,
                 'width': 120,
                 'height': 180,
                 'label': 'The Card'}]},
 {'name': 'Three Card Line',
  'description': 'The classic line — read as past / present / future, '
                 'situation / action / outcome, or any triad you prefer.',
  'positions': [{'x': 140,
                 'y': 80,
                 'width': 80,
                 'height': 120,
                 'label': 'Past'},
                {'x': 240,
                 'y': 80,
                 'width': 80,
                 'height': 120,
                 'label': 'Present'},
                {'x': 340,
                 'y': 80,
                 'width': 80,
                 'height': 120,
                 'label': 'Future'}]},
 {'name': 'Celtic Cross',
  'description': 'The classic 10-card Celtic Cross spread',
  'positions': [{'height': 120,
                 'label': 'Present',
                 'width': 80,
                 'x': 160,
                 'y': 180},
                {'height': 80,
                 'label': 'Challenge',
                 'rotated': True,
                 'width': 120,
                 'x': 160,
                 'y': 180},
                {'height': 120,
                 'label': 'Crown',
                 'width': 80,
                 'x': 160,
                 'y': 40,
                 'key': '3'},
                {'height': 120,
                 'label': 'Foundation',
                 'width': 80,
                 'x': 160,
                 'y': 320,
                 'key': '4'},
                {'height': 120,
                 'label': 'Past / Left Hand',
                 'width': 80,
                 'x': 60,
                 'y': 180},
                {'height': 120,
                 'label': 'Future / Right Hand',
                 'width': 80,
                 'x': 260,
                 'y': 180},
                {'height': 120,
                 'label': 'Self',
                 'width': 80,
                 'x': 380,
                 'y': 360},
                {'height': 120,
                 'label': 'Environment',
                 'width': 80,
                 'x': 380,
                 'y': 240},
                {'height': 120,
                 'label': 'Hopes/Fears',
                 'width': 80,
                 'x': 380,
                 'y': 120},
                {'height': 120,
                 'label': 'Outcome',
                 'width': 80,
                 'x': 380,
                 'y': 0}],
  'allowed_deck_types': ['Tarot'],
  'deck_slots': [{'cartomancy_type': 'Any', 'key': 'A'}]},
 {'name': 'Celtic Cross (w/ Significator)',
  'description': 'The classic 10-card Celtic Cross spread',
  'positions': [{'height': 90,
                 'key': 'S',
                 'label': 'Significator',
                 'width': 62,
                 'x': 120,
                 'y': 120,
                 'z_index': -1},
                {'height': 90,
                 'label': 'Present',
                 'width': 60,
                 'x': 140,
                 'y': 120,
                 'key': '1'},
                {'height': 60,
                 'label': 'Challenge',
                 'rotated': True,
                 'width': 90,
                 'x': 120,
                 'y': 140,
                 'key': '2'},
                {'height': 90,
                 'label': 'Crown',
                 'width': 60,
                 'x': 120,
                 'y': 20,
                 'key': '3'},
                {'height': 90,
                 'label': 'Foundation',
                 'width': 60,
                 'x': 120,
                 'y': 220,
                 'key': '4'},
                {'height': 90,
                 'label': 'Past / Left Hand',
                 'width': 60,
                 'x': 40,
                 'y': 120,
                 'key': '5'},
                {'height': 90,
                 'label': 'Future / Right Hand',
                 'width': 60,
                 'x': 220,
                 'y': 120,
                 'key': '6'},
                {'height': 90,
                 'label': 'Self',
                 'width': 60,
                 'x': 300,
                 'y': 296,
                 'key': '7'},
                {'height': 90,
                 'label': 'Environment',
                 'width': 60,
                 'x': 300,
                 'y': 200,
                 'key': '8'},
                {'height': 90,
                 'label': 'Hopes/Fears',
                 'width': 60,
                 'x': 300,
                 'y': 100,
                 'key': '9'},
                {'height': 90,
                 'key': '10',
                 'label': 'Outcome',
                 'width': 60,
                 'x': 300,
                 'y': 0}],
  'allowed_deck_types': ['Tarot'],
  'deck_slots': [{'cartomancy_type': 'Tarot', 'key': 'A'}]},
 {'name': 'Golden Dawn 15-Card',
  'description': '<p>The 15-card Golden Dawn/Thoth spread with five '
                 'elemental triads. Uses elemental dignities, not '
                 'reversals.<br><br>Card 1 represents the querent and the '
                 'nature of the problem and primary influences. A court '
                 'card (knight, queen, prince, princess) in this position '
                 'sometimes refers to a dominant individual or influence '
                 "in the querent's situation.</p><p>Cards 2 and 3 in "
                 'conjunction with card 1, are the key cards describing '
                 'the nature of the situation and the personality of the '
                 'querent.</p><p>Cards 13, 9 and 5, and 4, 8 and 12 in the '
                 'upper left and right indicate two potentials for the '
                 'future. They may compliment each other, in which case '
                 'the cards on the upper left are a development of the '
                 'cards on the upper right. If they are in conflict, the '
                 'cards on the upper right may be considered the direction '
                 "the querent's life will naturally follow unless action "
                 'is taken to change this course. The cards on the upper '
                 'left would then be possibilities of alternative '
                 'action.</p><p>Cards 6, 10 and 14 assist the querent in '
                 'making whatever decision may be necessary. They indicate '
                 'the psychological basis and implications of the '
                 'issue.</p><p>Cards 7, 11 and 15 show forces operating '
                 "beyond the querent's control—destiny or karma-to which "
                 'the querent can adapt. In this sense they constitute '
                 'advice as well.</p>',
  'positions': [{'height': 75,
                 'label': 'Significator',
                 'width': 50,
                 'x': 233,
                 'y': 150,
                 'key': '1'},
                {'height': 75,
                 'label': 'Describes Significator',
                 'width': 50,
                 'x': 175,
                 'y': 150,
                 'key': '2'},
                {'height': 75,
                 'label': 'Describes Significator',
                 'width': 50,
                 'x': 291,
                 'y': 150,
                 'key': '3'},
                {'height': 75,
                 'label': 'One Path',
                 'width': 50,
                 'x': 320,
                 'y': 50,
                 'key': '4'},
                {'height': 75,
                 'label': 'Another Path',
                 'width': 50,
                 'x': 146,
                 'y': 50,
                 'key': '5'},
                {'height': 75,
                 'label': 'Resources & Implications',
                 'width': 50,
                 'x': 146,
                 'y': 250,
                 'key': '6'},
                {'height': 75,
                 'label': 'Karma & Destiny',
                 'width': 50,
                 'x': 320,
                 'y': 250,
                 'key': '7'},
                {'height': 75,
                 'label': 'One Path',
                 'width': 50,
                 'x': 378,
                 'y': 50,
                 'key': '8'},
                {'height': 75,
                 'label': 'Another Path',
                 'width': 50,
                 'x': 88,
                 'y': 50,
                 'key': '9'},
                {'height': 75,
                 'label': 'Resources & Implications',
                 'width': 50,
                 'x': 88,
                 'y': 250,
                 'key': '10'},
                {'height': 75,
                 'label': 'Karma & Destiny',
                 'width': 50,
                 'x': 378,
                 'y': 251,
                 'key': '11'},
                {'height': 75,
                 'label': 'One Path',
                 'width': 50,
                 'x': 436,
                 'y': 50,
                 'key': '12'},
                {'height': 75,
                 'label': 'Another Path',
                 'width': 50,
                 'x': 30,
                 'y': 50,
                 'key': '13'},
                {'height': 75,
                 'label': 'Resources & Implications',
                 'width': 50,
                 'x': 30,
                 'y': 250,
                 'key': '14'},
                {'height': 75,
                 'label': 'Karma & Destiny',
                 'width': 50,
                 'x': 436,
                 'y': 250,
                 'key': '15'}],
  'allowed_deck_types': ['Tarot'],
  'deck_slots': [{'cartomancy_type': 'Tarot', 'key': 'A'}]},
 {'name': 'Grand Tableau (9x4)',
  'description': 'Full 36-card Lenormand Grand Tableau',
  'positions': [{'height': 60,
                 'key': '1',
                 'label': 'House of the Rider',
                 'width': 40,
                 'x': 0,
                 'y': 60},
                {'height': 60,
                 'key': '2',
                 'label': 'House of the Clover',
                 'width': 40,
                 'x': 60,
                 'y': 60},
                {'height': 60,
                 'key': '3',
                 'label': 'House of the Ship',
                 'width': 40,
                 'x': 120,
                 'y': 60},
                {'height': 60,
                 'key': '4',
                 'label': 'House of the Home',
                 'width': 40,
                 'x': 180,
                 'y': 60},
                {'height': 60,
                 'key': '5',
                 'label': 'House of the Tree',
                 'width': 40,
                 'x': 240,
                 'y': 60},
                {'height': 60,
                 'key': '6',
                 'label': 'House of the Clouds',
                 'width': 40,
                 'x': 300,
                 'y': 60},
                {'height': 60,
                 'key': '7',
                 'label': 'House of the Snake',
                 'width': 40,
                 'x': 360,
                 'y': 60},
                {'height': 60,
                 'key': '8',
                 'label': 'House of the Coffin',
                 'width': 40,
                 'x': 420,
                 'y': 60},
                {'height': 60,
                 'key': '9',
                 'label': 'House of the Bouquet',
                 'width': 40,
                 'x': 480,
                 'y': 60},
                {'height': 60,
                 'key': '10',
                 'label': 'House of the Scythe',
                 'width': 40,
                 'x': 0,
                 'y': 140},
                {'height': 60,
                 'key': '11',
                 'label': 'House of the Whip',
                 'width': 40,
                 'x': 60,
                 'y': 140},
                {'height': 60,
                 'key': '12',
                 'label': 'House of the Birds',
                 'width': 40,
                 'x': 120,
                 'y': 140},
                {'height': 60,
                 'key': '13',
                 'label': 'House of the Child',
                 'width': 40,
                 'x': 180,
                 'y': 140},
                {'height': 60,
                 'key': '14',
                 'label': 'House of the Fox',
                 'width': 40,
                 'x': 240,
                 'y': 140},
                {'height': 60,
                 'key': '15',
                 'label': 'House of the Bear',
                 'width': 40,
                 'x': 300,
                 'y': 140},
                {'height': 60,
                 'key': '16',
                 'label': 'House of the Stars',
                 'width': 40,
                 'x': 360,
                 'y': 140},
                {'height': 60,
                 'key': '17',
                 'label': 'House of the Stork',
                 'width': 40,
                 'x': 420,
                 'y': 140},
                {'height': 60,
                 'key': '18',
                 'label': 'House of the Dog',
                 'width': 40,
                 'x': 480,
                 'y': 140},
                {'height': 60,
                 'key': '19',
                 'label': 'House of the Tower',
                 'width': 40,
                 'x': 0,
                 'y': 220},
                {'height': 60,
                 'key': '20',
                 'label': 'House of the Garden',
                 'width': 40,
                 'x': 60,
                 'y': 220},
                {'height': 60,
                 'key': '21',
                 'label': 'House of the Mountain',
                 'width': 40,
                 'x': 120,
                 'y': 220},
                {'height': 60,
                 'key': '22',
                 'label': 'House of the Crossroads',
                 'width': 40,
                 'x': 180,
                 'y': 220},
                {'height': 60,
                 'key': '23',
                 'label': 'House of the Mice',
                 'width': 40,
                 'x': 240,
                 'y': 220},
                {'height': 60,
                 'key': '24',
                 'label': 'House of the Heart',
                 'width': 40,
                 'x': 300,
                 'y': 220},
                {'height': 60,
                 'key': '25',
                 'label': 'House of the Ring',
                 'width': 40,
                 'x': 360,
                 'y': 220},
                {'height': 60,
                 'key': '26',
                 'label': 'House of the Book',
                 'width': 40,
                 'x': 420,
                 'y': 220},
                {'height': 60,
                 'key': '27',
                 'label': 'House of the Letter',
                 'width': 40,
                 'x': 480,
                 'y': 220},
                {'height': 60,
                 'key': '28',
                 'label': 'House of the Man',
                 'width': 40,
                 'x': 0,
                 'y': 300},
                {'height': 60,
                 'key': '29',
                 'label': 'House of the Woman',
                 'width': 40,
                 'x': 60,
                 'y': 300},
                {'height': 60,
                 'key': '30',
                 'label': 'House of the Lily',
                 'width': 40,
                 'x': 120,
                 'y': 300},
                {'height': 60,
                 'key': '31',
                 'label': 'House of the Sun',
                 'width': 40,
                 'x': 180,
                 'y': 300},
                {'height': 60,
                 'key': '32',
                 'label': 'House of the Moon',
                 'width': 40,
                 'x': 240,
                 'y': 300},
                {'height': 60,
                 'key': '33',
                 'label': 'House of the Key',
                 'width': 40,
                 'x': 300,
                 'y': 300},
                {'height': 60,
                 'key': '34',
                 'label': 'House of the Fish',
                 'width': 40,
                 'x': 360,
                 'y': 300},
                {'height': 60,
                 'key': '35',
                 'label': 'House of the Anchor',
                 'width': 40,
                 'x': 420,
                 'y': 300},
                {'height': 60,
                 'key': '36',
                 'label': 'House of the Cross',
                 'width': 40,
                 'x': 480,
                 'y': 300}],
  'allowed_deck_types': ['Petit Lenormand'],
  'deck_slots': [{'cartomancy_type': 'Petit Lenormand', 'key': 'A'}]},
 {'name': 'Grand Tableau (8x4+4)',
  'description': 'Full 36-card Lenormand Grand Tableau, 8x4 with the four '
                 'fate cards centered beneath.',
  'positions': [{'x': 0,
                 'y': 0,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Rider',
                 'key': '1'},
                {'x': 60,
                 'y': 0,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Clover',
                 'key': '2'},
                {'x': 120,
                 'y': 0,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Ship',
                 'key': '3'},
                {'x': 180,
                 'y': 0,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Home',
                 'key': '4'},
                {'x': 240,
                 'y': 0,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Tree',
                 'key': '5'},
                {'x': 300,
                 'y': 0,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Clouds',
                 'key': '6'},
                {'x': 360,
                 'y': 0,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Snake',
                 'key': '7'},
                {'x': 420,
                 'y': 0,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Coffin',
                 'key': '8'},
                {'x': 0,
                 'y': 80,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Bouquet',
                 'key': '9'},
                {'x': 60,
                 'y': 80,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Scythe',
                 'key': '10'},
                {'x': 120,
                 'y': 80,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Whip',
                 'key': '11'},
                {'x': 180,
                 'y': 80,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Birds',
                 'key': '12'},
                {'x': 240,
                 'y': 80,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Child',
                 'key': '13'},
                {'x': 300,
                 'y': 80,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Fox',
                 'key': '14'},
                {'x': 360,
                 'y': 80,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Bear',
                 'key': '15'},
                {'x': 420,
                 'y': 80,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Stars',
                 'key': '16'},
                {'x': 0,
                 'y': 160,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Stork',
                 'key': '17'},
                {'x': 60,
                 'y': 160,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Dog',
                 'key': '18'},
                {'x': 120,
                 'y': 160,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Tower',
                 'key': '19'},
                {'x': 180,
                 'y': 160,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Garden',
                 'key': '20'},
                {'x': 240,
                 'y': 160,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Mountain',
                 'key': '21'},
                {'x': 300,
                 'y': 160,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Crossroads',
                 'key': '22'},
                {'x': 360,
                 'y': 160,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Mice',
                 'key': '23'},
                {'x': 420,
                 'y': 160,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Heart',
                 'key': '24'},
                {'x': 0,
                 'y': 240,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Ring',
                 'key': '25'},
                {'x': 60,
                 'y': 240,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Book',
                 'key': '26'},
                {'x': 120,
                 'y': 240,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Letter',
                 'key': '27'},
                {'x': 180,
                 'y': 240,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Man',
                 'key': '28'},
                {'x': 240,
                 'y': 240,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Woman',
                 'key': '29'},
                {'x': 300,
                 'y': 240,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Lily',
                 'key': '30'},
                {'x': 360,
                 'y': 240,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Sun',
                 'key': '31'},
                {'x': 420,
                 'y': 240,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Moon',
                 'key': '32'},
                {'x': 120,
                 'y': 320,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Key',
                 'key': '33'},
                {'x': 180,
                 'y': 320,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Fish',
                 'key': '34'},
                {'x': 240,
                 'y': 320,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Anchor',
                 'key': '35'},
                {'x': 300,
                 'y': 320,
                 'width': 40,
                 'height': 60,
                 'label': 'House of the Cross',
                 'key': '36'}],
  'allowed_deck_types': ['Petit Lenormand'],
  'deck_slots': [{'cartomancy_type': 'Petit Lenormand', 'key': 'A'}]},
 {'name': 'Lenormand 3-Card',
  'description': 'Simple three-card Lenormand line',
  'positions': [{'x': 60,
                 'y': 80,
                 'label': '1',
                 'width': 80,
                 'height': 120},
                {'x': 160,
                 'y': 80,
                 'label': '2',
                 'width': 80,
                 'height': 120},
                {'x': 260,
                 'y': 80,
                 'label': '3',
                 'width': 80,
                 'height': 120}],
  'allowed_deck_types': ['Petit Lenormand'],
  'deck_slots': [{'key': 'A', 'cartomancy_type': 'Petit Lenormand'}]},
 {'name': 'Lenormand 3x3 Box',
  'description': 'Nine-card Lenormand box spread',
  'positions': [{'height': 120,
                 'label': '1',
                 'width': 80,
                 'x': 60,
                 'y': 20},
                {'height': 120,
                 'label': '2',
                 'width': 80,
                 'x': 160,
                 'y': 20},
                {'height': 120,
                 'label': '3',
                 'width': 80,
                 'x': 260,
                 'y': 20},
                {'height': 120,
                 'label': '4',
                 'width': 80,
                 'x': 60,
                 'y': 160},
                {'height': 120,
                 'label': '5',
                 'width': 80,
                 'x': 160,
                 'y': 160},
                {'height': 120,
                 'label': '6',
                 'width': 80,
                 'x': 260,
                 'y': 160},
                {'height': 120,
                 'label': '7',
                 'width': 80,
                 'x': 60,
                 'y': 300},
                {'height': 120,
                 'label': '8',
                 'width': 80,
                 'x': 160,
                 'y': 300},
                {'height': 120,
                 'label': '9',
                 'width': 80,
                 'x': 260,
                 'y': 300}],
  'allowed_deck_types': ['Petit Lenormand'],
  'deck_slots': [{'cartomancy_type': 'Petit Lenormand', 'key': 'A'}]},
 {'name': 'Wheel of the Year',
  'description': '<p>Each of the twelve cards in the circle describes a '
                 'month, starting at the top. If done at the New Year the '
                 'top is January. The center is the overall theme of the '
                 'year</p>',
  'positions': [{'height': 120,
                 'key': '1',
                 'label': 'Month 1',
                 'width': 80,
                 'x': 400,
                 'y': 0,
                 'z_index': 0},
                {'height': 120,
                 'key': '2',
                 'label': 'Month 2',
                 'width': 80,
                 'x': 540,
                 'y': 120,
                 'z_index': 1},
                {'height': 120,
                 'key': '3',
                 'label': 'Month 3',
                 'width': 80,
                 'x': 680,
                 'y': 240,
                 'z_index': 2},
                {'height': 120,
                 'key': '4',
                 'label': 'Month 4',
                 'width': 80,
                 'x': 820,
                 'y': 360,
                 'z_index': 3},
                {'height': 120,
                 'key': '5',
                 'label': 'Month 5',
                 'width': 80,
                 'x': 680,
                 'y': 480,
                 'z_index': 4},
                {'height': 120,
                 'key': '6',
                 'label': 'Month 6',
                 'width': 80,
                 'x': 540,
                 'y': 600,
                 'z_index': 5},
                {'height': 120,
                 'key': '7',
                 'label': 'Month 7',
                 'width': 80,
                 'x': 420,
                 'y': 720,
                 'z_index': 6},
                {'height': 120,
                 'key': '8',
                 'label': 'Month 8',
                 'width': 80,
                 'x': 280,
                 'y': 600,
                 'z_index': 7},
                {'height': 120,
                 'key': '9',
                 'label': 'Month 9',
                 'width': 80,
                 'x': 140,
                 'y': 480,
                 'z_index': 8},
                {'height': 120,
                 'key': '10',
                 'label': 'Month 10',
                 'width': 80,
                 'x': 0,
                 'y': 360,
                 'z_index': 9},
                {'height': 120,
                 'key': '11',
                 'label': 'Month 11',
                 'width': 80,
                 'x': 140,
                 'y': 220,
                 'z_index': 10},
                {'height': 120,
                 'key': '12',
                 'label': 'Month 12',
                 'width': 80,
                 'x': 260,
                 'y': 120,
                 'z_index': 11},
                {'height': 120,
                 'key': '13',
                 'label': 'Central Theme',
                 'width': 80,
                 'x': 400,
                 'y': 340,
                 'z_index': 12}],
  'deck_slots': [{'cartomancy_type': 'Tarot',
                  'key': 'A',
                  'label': 'Main Deck'}]}]
